"""Config generation screen (Phase 12 §2g).

Renders a ``config.toml`` from wizard state, offers an editable preview, and
writes it to the project root (backing up any existing file first). The core
``generate_config`` function is unit-testable without a running Textual app.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from textual.app import ComposeResult
from textual.screen import Screen
from textual.widgets import Button, Input, Label, Static, TextArea

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ConfigInputs:
    """User-provided inputs that drive ``config.toml`` generation."""

    project_name: str = "Mediaite AI Writing Survey"
    baseline_start: str = "2020-01-01"
    baseline_end: str = "2023-12-31"
    mode: str = "blind"  # "blind" | "pick"
    author_slugs: tuple[str, ...] = ()


def generate_config(inputs: ConfigInputs) -> str:
    """Render a complete, runnable ``config.toml`` from ``inputs``.

    The output intentionally contains *no* placeholder strings like
    ``FIXME``/``TODO`` — every field either has a user-provided value or a
    documented default. Tests rely on this invariant.
    """
    lines: list[str] = []
    lines.append("# Generated by forensics setup wizard")
    lines.append(f"# Project: {inputs.project_name}")
    lines.append("")

    if inputs.mode == "blind":
        lines.append("# Blind survey mode — authors are discovered and qualified automatically.")
        lines.append("# The [[authors]] block below seeds the scraper with a placeholder entry")
        lines.append("# so the pipeline boots cleanly; the survey orchestrator ignores roles.")
        lines.append("")
        lines.append("[[authors]]")
        lines.append('name = "Survey Seed"')
        lines.append('slug = "survey-seed"')
        lines.append('outlet = "mediaite.com"')
        lines.append('role = "target"')
        lines.append('archive_url = "https://www.mediaite.com/author/survey-seed/"')
        lines.append(f"baseline_start = {inputs.baseline_start}")
        lines.append(f"baseline_end = {inputs.baseline_end}")
        lines.append("")
    else:
        if not inputs.author_slugs:
            # Hand-pick mode with no slugs entered — emit a documented stub
            # so the file is valid TOML without inserting placeholder text.
            lines.append("# Hand-pick mode: add author blocks below before running the pipeline.")
            lines.append("# Example (uncomment and edit):")
            lines.append("# [[authors]]")
            lines.append('# name = "Author Name"')
            lines.append('# slug = "author-slug"')
            lines.append('# outlet = "mediaite.com"')
            lines.append('# role = "target"')
            lines.append('# archive_url = "https://www.mediaite.com/author/author-slug/"')
            lines.append(f"# baseline_start = {inputs.baseline_start}")
            lines.append(f"# baseline_end = {inputs.baseline_end}")
            lines.append("")
        else:
            for slug in inputs.author_slugs:
                lines.append("[[authors]]")
                lines.append(f'name = "{slug.replace("-", " ").title()}"')
                lines.append(f'slug = "{slug}"')
                lines.append('outlet = "mediaite.com"')
                lines.append('role = "target"')
                lines.append(f'archive_url = "https://www.mediaite.com/author/{slug}/"')
                lines.append(f"baseline_start = {inputs.baseline_start}")
                lines.append(f"baseline_end = {inputs.baseline_end}")
                lines.append("")

    lines.extend(
        [
            "[scraping]",
            "rate_limit_seconds = 2.0",
            "jitter = 0.5",
            "max_concurrent = 3",
            "max_retries = 3",
            "",
            "[analysis]",
            "rolling_windows = [30, 90]",
            "significance_threshold = 0.05",
            'embedding_model = "sentence-transformers/all-MiniLM-L6-v2"',
            'changepoint_methods = ["pelt", "bocpd"]',
            "",
            "[survey]",
            "min_articles = 50",
            "min_span_days = 730",
            "min_words_per_article = 200",
            "min_articles_per_year = 12.0",
            "require_recent_activity = true",
            "recent_activity_days = 180",
            "",
            "[baseline]",
            'models = ["llama3.2:latest"]',
            "",
            "[chain_of_custody]",
            "verify_corpus_hash = true",
            "verify_raw_archives = true",
            "",
            "[report]",
            'output_format = "html"',
            "",
        ]
    )

    return "\n".join(lines)


def write_config(target: Path, contents: str, *, backup: bool = True) -> Path | None:
    """Write ``config.toml``, optionally backing up an existing file.

    Returns the backup path (or ``None`` when no backup was written).
    """
    backup_path: Path | None = None
    if target.exists() and backup:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_path = target.with_suffix(target.suffix + f".{timestamp}.bak")
        backup_path.write_bytes(target.read_bytes())
        logger.info("config: backed up existing file to %s", backup_path)
    target.write_text(contents, encoding="utf-8")
    return backup_path


def _inputs_from_state(state: dict[str, Any]) -> ConfigInputs:
    return ConfigInputs(
        project_name=str(state.get("project_name", "Mediaite AI Writing Survey")),
        baseline_start=str(state.get("baseline_start", "2020-01-01")),
        baseline_end=str(state.get("baseline_end", "2023-12-31")),
        mode=str(state.get("mode", "blind")),
        author_slugs=tuple(state.get("author_slugs", ())),
    )


class ConfigGenerationScreen(Screen):
    """Screen 3: edit and write ``config.toml``."""

    def compose(self) -> ComposeResult:
        yield Label("Step 3 of 5: Configuration", id="step-label")
        yield Static("Review the generated config.toml below and adjust as needed.", id="status")
        yield Input(
            placeholder="Project name",
            id="project-name",
            value="Mediaite AI Writing Survey",
        )
        yield Input(
            placeholder="Baseline start (YYYY-MM-DD)",
            id="baseline-start",
            value="2020-01-01",
        )
        yield Input(
            placeholder="Baseline end (YYYY-MM-DD)",
            id="baseline-end",
            value="2023-12-31",
        )
        yield Input(
            placeholder="Author slugs (comma-separated, hand-pick mode only)",
            id="author-slugs",
        )
        yield TextArea(id="config-editor", language="toml")
        yield Button("Refresh preview", id="refresh-btn", variant="default")
        yield Button("Write config.toml", id="write-btn", variant="primary")
        yield Button("Continue (n)", id="next-btn", variant="success")

    def on_mount(self) -> None:
        self._refresh_preview()

    def _current_inputs(self) -> ConfigInputs:
        state = dict(self.app.wizard_state)
        state.setdefault("mode", "blind")
        try:
            state["project_name"] = self.query_one("#project-name", Input).value
            state["baseline_start"] = self.query_one("#baseline-start", Input).value
            state["baseline_end"] = self.query_one("#baseline-end", Input).value
            slugs_raw = self.query_one("#author-slugs", Input).value
        except Exception:  # noqa: BLE001 - widgets not mounted yet
            slugs_raw = ""
        slugs = tuple(s.strip() for s in slugs_raw.split(",") if s.strip())
        if slugs:
            state["author_slugs"] = slugs
            state["mode"] = "pick"
        return _inputs_from_state(state)

    def _refresh_preview(self) -> None:
        editor = self.query_one("#config-editor", TextArea)
        editor.text = generate_config(self._current_inputs())

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "refresh-btn":
            self._refresh_preview()
        elif event.button.id == "write-btn":
            from forensics.config import get_project_root

            target = get_project_root() / "config.toml"
            editor = self.query_one("#config-editor", TextArea)
            backup = write_config(target, editor.text)
            status = self.query_one("#status", Static)
            if backup is not None:
                status.update(f"Wrote {target} (previous config backed up to {backup.name}).")
            else:
                status.update(f"Wrote {target}.")
        elif event.button.id == "next-btn":
            self.app.action_next_step()


__all__ = [
    "ConfigGenerationScreen",
    "ConfigInputs",
    "generate_config",
    "write_config",
]
